// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCve5XbgWim1KWUvZFkQ8QLCcJu6dVuPMI',
    appId: '1:878957561132:web:e6f66e8e2236f91f0f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    authDomain: 'soul-shake.firebaseapp.com',
    storageBucket: 'soul-shake.appspot.com',
    measurementId: 'G-DFR0TQYNY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo9KxVPVzyUHQHAGMzvDtUQxxM2mVdgnc',
    appId: '1:878957561132:android:ce8cc5c711831c8a0f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    storageBucket: 'soul-shake.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiavNHefhu3r21Xki8wxzftS_gxHvhFoA',
    appId: '1:878957561132:ios:0caf577e8ee9ffc60f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    storageBucket: 'soul-shake.appspot.com',
    iosClientId:
        '878957561132-r3v4tdcdnfh27m8hp0106s995cin14u2.apps.googleusercontent.com',
    iosBundleId: 'co.uk.flutterly.prayerHotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiavNHefhu3r21Xki8wxzftS_gxHvhFoA',
    appId: '1:878957561132:ios:0caf577e8ee9ffc60f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    storageBucket: 'soul-shake.appspot.com',
    iosClientId:
        '878957561132-r3v4tdcdnfh27m8hp0106s995cin14u2.apps.googleusercontent.com',
    iosBundleId: 'co.uk.flutterly.prayerHotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCve5XbgWim1KWUvZFkQ8QLCcJu6dVuPMI',
    appId: '1:878957561132:web:2c35b3b1839f9c5c0f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    authDomain: 'soul-shake.firebaseapp.com',
    storageBucket: 'soul-shake.appspot.com',
    measurementId: 'G-91HDBG1PY3',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCve5XbgWim1KWUvZFkQ8QLCcJu6dVuPMI',
    appId: '1:878957561132:web:58043196686c97a80f9889',
    messagingSenderId: '878957561132',
    projectId: 'soul-shake',
    authDomain: 'soul-shake.firebaseapp.com',
    storageBucket: 'soul-shake.appspot.com',
    measurementId: 'G-T7YXHXJTND',
  );
}
